# Generated by Django 4.1.4 on 2023-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_category_options_alter_donation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(null=True),
        ),
    ]
